---
language: node_js
node_js:
  - "6"

sudo: false

addons:
    firefox: "latest"

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_install:
  - yarn global add bower phantomjs-prebuilt
  - bower --version
  - phantomjs --version
  - bower install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:each
